### ISSUE TITLE
Editor tab is not visible

### ISSUE THREAD

**Issue by ehsandeep** [maxence-schmitt/OfficeOpenXMLEditor#1]
Hi, Thanks for doing this.

I just successfully install it on my burp without any error, and uploaded `.doc` deliberately on internet but neither the Office proxy history tab  showing Open XML editor in while uploading the `.doc` file  nor in repeater tab as well, and I double check, the default content type which is already mentioned in **conf** file, so just curious for what reason I'm not able to see the editor tab, is there additional steps I need to take ?

**Installation which is did:** 

1. Cloned the repo on storage.
2. Installed OfficeOpenXMLEditor.py via extender tab.

![image](https://user-images.githubusercontent.com/8293321/32865436-25cf22c4-ca89-11e7-8afd-60dc6e3893b3.png)

**Comment by ehsandeep** [comment]
![image](https://user-images.githubusercontent.com/8293321/32866004-a221c74e-ca8b-11e7-82ca-7b91c7cea2ca.png)

I was trying to upload the document here: http://www.verypdf.com/online/free-online-document-sharing.php

**Comment by maxence-schmitt** [comment]
Hi, thanks for the feedbacks, you haveinstalled the extension properly. 
I was able to reproduce the issue, sorry for this I will look at it and keep you upated.

**Comment by maxence-schmitt** [comment]
Hi, I found the issue and fix it in the following branch:
https://github.com/maxence-schmitt/OfficeOpenXMLEditor/tree/bug-PR1-Tab_not_visible
Can you, please, confirm it's working for you, so I can merge it?
Thanks in advance.

**Comment by ehsandeep** [comment]
![image](https://user-images.githubusercontent.com/8293321/32943930-c5203e00-cbb3-11e7-82bd-cf74f7aa12dd.png)

Fixed 👍  Thanks.

Just curious if we can edit multiple files at once other than `[Content_Types].xml` or just single files at once? if not would like to request for that feature if its possible.

**Comment by maxence-schmitt** [comment]
Good, welcome !
Today, it's only possible to modify on file at a time...
But it's a good idea, I will have to check how complicated it is to add this.
